services:
  worker:
    image: dairoot/chatgpt-mirror:latest
    volumes:
      - ./admin/dist:/tmp/dist
      - chatgpt_data:/app/worker/.wrangler
    environment: # 管理后台账号密码 （请更改此账号密码，并取消注释）
      - ADMIN_USERNAME=zhroot
      - ADMIN_PASSWORD=zhroot

    ports:
      - "50001-50002:8787"
    deploy:
      replicas: 2
    restart: always

volumes:
  chatgpt_data:
